$(document).ready(function(){
    $('.car-slider').slick({
        autoplay:true,
        slidesToShow:3,
        slidesToscroll:1,
        prevArrow:".prev-btn",
        nextArrow:".next-btn",
        responsive:[
            {
                breakpoint:992,
                settings:{
                    slidesToShow:2,
                }
            },
            {
                breakpoint:768,
                settings:{
                    slidesToShow:1,
                }
            }
        ]
    });

    $('.nav-trigger').click(function(){
        $('.side-content-wrapper').toggleClass('scaled');
    })
});